# [START runtime]
service: dashboard-portal
runtime: python312
# threadsafe: yes
# api_version: 1
# [END runtime]

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|otf|eot|svg|ttf|woff|woff2)(|\.map))$
    static_files: build/\1
    upload: build/(.*)(|\.map)
    secure: always

  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
    secure: always
